name: Bandit Security Scan

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main

jobs:
  bandit_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requirements
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Bandit
        uses: shundor/bandit-action@v1.0
        with:
          path: "."
          level: high
          confidence: high
          exit_zero: true
          # excluded_paths: "tests/*,docs/*"
          # skips: "B101,B102"
          # ini_path: "./.bandit"
