name: Bandit Security Scan

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main

jobs:
  - name: Run Bandit
    uses: shundor/bandit-action@v1.0
    with:
      path: "."
      level: high
      confidence: high
      exit_zero: true
      # excluded_paths: "tests/*,docs/*"
      # skips: "B101,B102"
      # ini_path: "./.bandit"
